### ISSUE TITLE
BAND parameter error

### ISSUE THREAD

**Issue by WangariKimotho** [pinakographos/Hachures#13]
I experienced this on **QGIS version 3.32.2-Lima** for mac when trying to run the code with the provided(and other) dem tif files. 

**Here is the error: 
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 63, in <module>
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/tools/general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing/core/Processing.py", line 170, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for BAND**

**Comment by pinakographos** [comment]
Interesting. Thanks for mentioning this. Unfortunately, I'm not able to reproduce this locally with the sample DEM (on 3.34.11-Prizren on a Mac). The line numbers mentioned in the error also don't seem to align with what I'd expect — they're not pointing at parts of the script that deal with bands, for example.

This is a bit of a mystery, unfortunately. I can leave this open for now to see if anyone else has this issue, or until something comes up that lets me reproduce it.

**Comment by PietrH** [comment]
I was able to replicate this in 3.32.2-Lima on Ubuntu, first with my own layer, then with the sample DEM. 

```log
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/script/ScriptEditorDialog.py", line 260, in runAlgorithm
    exec(self.editor.text(), _locals)
  File "<string>", line 62, in <module>
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 170, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for BAND

```

**Comment by PietrH** [comment]
I now updated to 3.40.0, and am now getting a different error ;

```
Traceback (most recent call last):
  File "/app/share/qgis/python/plugins/processing/script/ScriptEditorDialog.py", line 255, in runAlgorithm
    exec(self.editor.text(), _locals)
  File "<string>", line 649, in <module>
TypeError: 'NoneType' object is not iterable
```

I was able to run the sample DEM in a new project, but am getting transformation errors on my own layer, something about a transformation to NAD83 / Michigan Oblique Mercator not being available? I'm making a map in west africa so I'm not sure transforming to a Michigan local datum is such a great idea? 

I was reprojecting a layer myself, when avoiding this, I can get the script to output a hachures layer, ~~but displaced, so it seems it's outputting in the wrong projection now.~~ The scale is actually massively wrong. The location is correct. I still get an error when running: 
![image](https://github.com/user-attachments/assets/7d1e4a1c-ed42-49a7-90bd-58954dc59c81)


Is there anything I can provide to help troubleshoot this? 

---

My hunch was correct, It's both displaced and out of scale:

![image](https://github.com/user-attachments/assets/d7038571-e5d3-4d8f-aebb-ba5be733a483)

This is after scaling by 117000 on both the x and y axis, on the left some contours I calculated, in the correct spot. And to the right, the hachures.

**Comment by pinakographos** [comment]
Thanks for replicating this. I am traveling at the moment, but I will poke
at this when I get a chance. The Michigan coordinate system is the one that
the sample DEM uses. Not sure why QGIS would be using that one, unless you
had previously loaded in the sample DEM, then loaded in some other layers
that it was trying to convert to that system.

Once I get a chance to work on this, I may also pass back some modified
code that is more verbose in reporting back errors (or parts that are
working), to help me figure this out since I can't reproduce it on my own
system. Once I return home I also have another computer I can run things
on, which might help give me other situations to test it in.

Meanwhile, if you find anything else out before I have a chance to work on
this, do let me know!

**Comment by pinakographos** [comment]
Ok, back again. I have made some adjustments to a branch of the code which might get at these issues. If you could both give things a try, @WangariKimotho and @PietrH, I would be appreciative. The new code [is here](https://github.com/pinakographos/Hachures/blob/NextGen/Hachure%20Generator.py).

I cannot reproduce the BAND issue myself, but I have added an explicit declaration of the band, which may help if different versions of both QGIS and its various dependencies aren't assuming the band to be 1.

I've also adjusted where the script pulls the CRS of the lines from. It used to look at the project instance's CRS, but now it looks at the DEM's which should be more correct and will let you run the tool on a DEM that's in a different CRS than the instance. I usually keep my DEMs in the same instance as the project during a lot of my workflow, so I never noticed this.

Please let me know if these adjustments have helped!
